name: flood
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - gdal
  - rasterio
  - fiona
  - geopandas
  - shapely
  - pyproj
  - pandas
  - numpy
  - matplotlib
  - folium
  - requests
  - pytest
